stages:
  collect:
    cmd: python collect_data.py
    outs:
      - data/raw_data.csv
  preprocess:
    cmd: python preprocess.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train:
    cmd: python train.py
    deps:
      - data/processed_data.csv
    outs:
      - model/model.pkl
